AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - app/admin/*.rb
    - db/migrate/*.rb

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 30

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Block/FrozenStringLiteralComment:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Metrics/AbcSize:
  Max: 30
